### ISSUE TITLE
RTS and Say the Spire prevent each other from loading

### ISSUE THREAD

**Issue by ObjectInSpace** [pitermach/ReadTheSpire#6]
If I play the game with TTS and STS both selected in mod manager, RTS gives a "Failed to load tolk.dll" error when I attempt to launch it. Subsequently closing the game causes tolk.dll to be deleted. (! ?)

If I launch RTS and then attempt to launch the game with TTS and STS enabled, the game fails to launch with the following output:

exception thrown
E:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\Tolk.dll (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: E:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\Tolk.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at sayTheSpire.speech.TolkResourceHandler.loadResources(TolkResourceHandler.java:34)
	at sayTheSpire.speech.SpeechManager.setup(SpeechManager.java:53)
	at sayTheSpire.Output.setup(Output.java:49)
	at CardCrawlGamePatch$CardCrawlGameCreatePatch.Postfix(CardCrawlGamePatch.java:13)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:308)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: E:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\Tolk.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.UnsatisfiedLinkError: E:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\Tolk.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.davykager.tolk.Tolk.<clinit>(Tolk.java:34)
	at sayTheSpire.speech.TolkHandler.load(TolkHandler.java:20)
	at sayTheSpire.speech.SpeechManager.setup(SpeechManager.java:54)
	at sayTheSpire.Output.setup(Output.java:49)
	at CardCrawlGamePatch$CardCrawlGameCreatePatch.Postfix(CardCrawlGamePatch.java:13)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:308)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)

	at com.

**Comment by pitermach** [comment]
Were you trying to run ReadTheSpire from the SlayTheSpire directory?
At first I wasn't able to reproduce this, but I suspected it might have something to do with working directories so I tried to copy it in there and I got the same problem.

- Read The Spire is a 32-bit app and so comes with 32-bit dll's. The game itself meanwhile is 64-bit, so SayTheSpire needs a 64-bit version of Tolk to load. So when it tries loading and sees the DLL that RTS comes with, it tries to load that which fails, and if you go the other way it'll install its own 64-bit DLL which in turn RTS can't load and then it gets deleted all together when STS cleans up after itself.

So just move ReadTheSpire somewhere else and try running it from there. If this helps, I'll update the documentation

**Comment by sukiletxe** [comment]
I don't know where Say the Spire is installed, but if I run Read the Spire from another directory (if you must, "C:\Users\sukil\OneDrive\programas\juegos\RTS\rts.exe") they both run fine.
